name: Scheduled Python Script

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade openpyxl pandas requests msal
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Verify OpenPyXL Installation
        run: python -c "import openpyxl; print('Openpyxl version:', openpyxl.__version__)"

      - name: Run Python scripts
        run: |
          python ScheduledBinanceDataCollectionCode.py
          python ScheduledBitgetDataCollectionCode.py
          python ScheduledBybitDataCollectionCode.py
          python ScheduledGateioDataCollectionCode.py
          python ScheduledKuCoinDataCollectionCode.py
          python ScheduledMexcDataCollectionCode.py
          python ScheduledOkxDataCollectionCode.py

      - name: Commit and Push Changes
        env:
          GITHUB_PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin
          if git show-ref --verify --quiet refs/remotes/origin/main; then
            git checkout main
          else
            git checkout -b main
            git push origin main
          fi
          git pull --rebase origin main
          git add .
          git commit -m "Automated update - $(date)" || echo "No changes to commit"
          git push origin main
