name: Scheduled Python Script

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  push:
    branches:
      - data
  pull_request:
    branches:
      - data 
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Git user
        run: git config --global user.email "actions@github.com"

      - name: Set up Git user name
        run: git config --global user.name "GitHub Actions"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade openpyxl pandas requests msal

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Verify OpenPyXL Installation
        run: python -c "import openpyxl; print('Openpyxl version:', openpyxl.__version__)"  # ✅ Debugging step

      - name: Run Python script
        run: |
          python ScheduledBinanceDataCollectionCode.py
          python ScheduledBitgetDataCollectionCode.py
        # python ScheduledBybitDataCollectionCode.py
        # python ScheduledGateioDataCollectionCode.py

      - name: Commit and Push Changes
        env:
          GITHUB_PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout data
          git pull --rebase origin data
          git add .
          git commit -m "Automated update - $(date)" || echo "No changes to commit"
          git push origin data || (git pull --rebase origin data && git push origin data)


      
      # - name: commit files
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add -A
      #     git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      # - name: push changes
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: data 
