name: Scheduled Python Script

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script
        run: |
          ScheduledBinanceDataCollectionCode.py
          
      - name: Run Python script
        run: |
          python ScheduledBinanceDataCollectionCode.py

      - name: Run Python script
        run: |
          ScheduledBitgetDataCollectionCode.py

      - name: Run Python script
        run: |
          ScheduledBybitDataCollectionCode.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
